title: joaxcar
description: My very nice blog
author: "Johan Carlsson"

theme: minima

# Minima: show excerpts in the frontpage
show_excerpts: true

twitter_username: joaxcar
github_username: joaxcar
linkedin_username: joaxcar

minima:
  date_format: "%Y-%m-%d"
  social_links:
    twitter: joaxcar
    github:  joaxcar

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/links.md
  - _pages/archive.md

include:
    - _pages
    - sop

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
